import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>{`Tate's Portfolio`}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* useRef + scrolling for one page scrolling to different pages */}

      <div className={styles.homegrid}>
        <div className={styles.homeprofilecard}>
            <div className={styles.homepfp}>
                <Image
                    className={styles.pfpimg}
                    src='/portrait.jpg'
                    alt='Tate Bonham'
                    width={400}
                    height={500}
                />
            </div>
            <div className={styles.homeinfo}>
                <h1>Tate Bonham</h1>
                <h2>Full Stack Software Engineer</h2>
                <p>Phone: 480-452-5737</p>
                <p>Email: tatebonham@gmail.com</p>
                <p>Slack: @tatebonham</p>
                <div> 
                <a className={styles.icon} href='https://github.com/tatebonham' >
                  <Image
                        className={styles.iconimg}
                        src='/github.png'
                        alt='Tate Bonham'
                        width={100}
                        height={100}
                      />
                      </a>
                      <a className={styles.icon} href='https://www.linkedin.com/in/tate-bonham/'  ><Image
                        className={styles.iconimg}
                        src='/linkedin.png'
                        alt='Tate Bonham'
                        width={100}
                        height={100}
                      /></a>
                      <a className={styles.icon} href='/ResumeTateBonham.pdf'  ><Image
                        className={styles.iconimg}
                        src='/Resume.png'
                        alt='Tate Bonham'
                        width={100}
                        height={100}
                      /></a></div>
            </div>
        </div>
        {/* <div className={styles.headertext}>
          <div>
            <h1>Tate Bonham</h1>
          </div>
          <p>Hey I'm Tate, a Full Stack Software Engineer from Arizona.</p>
          <p> Former: Manager, IT Specialist, and Data Entry</p>
          <p>Most recent hobbies are embroidery, woodworking and D&D </p>
          <p>but they change every few months so I'm always learning something new!</p>
          <div>
            <p><a href='/resume.pdf' className={styles.link}  >Check out my resume here!</a></p>
          </div>
        </div> */}
        <div className={styles.skilltext}><h2 className={styles.skillh2}>Skills</h2></div>
      <div className={styles.skills}><h4>HTML | CSS | Javascript | React | Python | Node | Express | Git | MongoDB | SQL | SASS/SCSS  </h4></div>
      <div className={styles.skillsicons}>
                <Image
                    className={styles.skillimg}
                    src='/hcj.png'
                    alt='Tate Bonham'
                    width={200}
                    height={100}
                />  
                <Image
                    className={styles.skillimg}
                    src='/react2.png'
                    alt='Tate Bonham'
                    width={80}
                    height={80}
                />  
                <Image
                    className={styles.skillimg}
                    src='/Python.png'
                    alt='Tate Bonham'
                    width={80}
                    height={80}
                />  
                <Image
                    className={styles.skillimg}
                    src='/node.png'
                    alt='Tate Bonham'
                    width={80}
                    height={80}
                />  
                <Image
                    className={styles.skillimg}
                    src='/express3.png'
                    alt='Tate Bonham'
                    width={80}
                    height={80}
                />  
                <Image
                    className={styles.skillimg}
                    src='/git.png'
                    alt='Tate Bonham'
                    width={80}
                    height={80}
                />  
                <Image
                    className={styles.skillimg}
                    src='/mongo.png'
                    alt='Tate Bonham'
                    width={80}
                    height={80}
                />  
                <Image
                    className={styles.skillimg}
                    src='/sql.png'
                    alt='Tate Bonham'
                    width={80}
                    height={80}
                />  
                <Image
                    className={styles.skillimg}
                    src='/sass.png'
                    alt='Tate Bonham'
                    width={80}
                    height={80}
                />  
                </div>
        
      </div>
    </div>
  )
}
